{
 "title": "EC2",
 "description": "Dashboard for EC2 Instances based on metrics from AWS CloudWatch metrics stream",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "EC2_Instance_Identifier",
    "label": "EC2 Instance Identifier",
    "query": {
     "query": "label_values(amazonaws_com_AWS_EC2_CPUUtilization{}, InstanceId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "The percentage of CPU Utilization.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (InstanceId) (amazonaws_com_AWS_EC2_CPUUtilization_sum{InstanceId=~'$EC2_Instance_Identifier'}) / sum by (InstanceId) (amazonaws_com_AWS_EC2_CPUUtilization_count{InstanceId=~'$EC2_Instance_Identifier'})"
    }
   ]
  },
  {
   "title": "Status Check Failed",
   "type": "timeseries",
   "description": "Status Check Failed",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (InstanceId) (amazonaws_com_AWS_EC2_StatusCheckFailed_sum{InstanceId=~'$EC2_Instance_Identifier'})"
    }
   ]
  },
  {
   "title": "CPU Credit Balance",
   "type": "timeseries",
   "description": "CPU Credit Balance",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (InstanceId) (amazonaws_com_AWS_EC2_CPUCreditBalance{InstanceId=~'$EC2_Instance_Identifier', quantile='0'})"
    }
   ]
  },
  {
   "title": "Network In",
   "type": "timeseries",
   "description": "Network out bytes",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (InstanceId) (amazonaws_com_AWS_EC2_NetworkIn_sum{InstanceId=~'$EC2_Instance_Identifier'})"
    }
   ]
  },
  {
   "title": "CPU surplus credits charged",
   "type": "timeseries",
   "description": "CPU surplus credits charged",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (InstanceId) (amazonaws_com_AWS_EC2_CPUSurplusCreditsCharged_sum{InstanceId=~'$EC2_Instance_Identifier'})"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "timeseries",
   "description": "Network out bytes",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (InstanceId) (amazonaws_com_AWS_EC2_NetworkOut_sum{InstanceId=~'$EC2_Instance_Identifier'})"
    }
   ]
  },
  {
   "title": "EBS IO Balance",
   "type": "timeseries",
   "description": "EBS IO Balance",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (InstanceId) (amazonaws_com_AWS_EC2_EBSIOBalance_{InstanceId=~'$EC2_Instance_Identifier', quantile='0'})"
    }
   ]
  },
  {
   "title": "EBS Byte Balance",
   "type": "timeseries",
   "description": "EBS Byte Balance",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (InstanceId) (amazonaws_com_AWS_EC2_EBSByteBalance_{InstanceId=~'$EC2_Instance_Identifier', quantile='0'})"
    }
   ]
  }
 ]
}