extensions:
  basicauth/prw:
    client_auth:
      # Replace these variables by their actual values
      username: $levitate_username
      password: $levitate_password

receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector-01'
        scrape_interval: 60s
        static_configs:
        - targets: ['otel-collector:8888', 'app:8000']

exporters:
  prometheusremotewrite:
    auth:
      authenticator: basicauth/prw
    endpoint: "$levitate_write_endpoint" # Replace this variable by its actual value

service:
  extensions: [basicauth/prw]
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [prometheusremotewrite]
