version: '3.6'
services:
  statsd:
    build: statsd
    depends_on:
      - vmagent_levitate
    ports:
      - 8125:8125/udp
      - 8126:8126/udp
    restart: always

  vmagent_levitate:
    image: victoriametrics/vmagent:v1.85.3
    ports:
      - 8429:8429
      - 2003:2003/tcp
      - 2003:2003/udp
    volumes:
      - vmagentdata:/vmagentdata
      - ./vmagent.yaml:/etc/prometheus/prometheus.yaml
    command:
      - "--graphiteListenAddr=:2003"
      - "--promscrape.config=/etc/prometheus/prometheus.yaml"
      - "--remoteWrite.url=${LEVITATE_REMOTE_WRITE_URL}"
      - "--remoteWrite.basicAuth.username=${LEVITATE_REMOTE_WRITE_USERNAME}"
      - "--remoteWrite.basicAuth.password=${LEVITATE_REMOTE_WRITE_PASSWORD}"
    restart: always

volumes:
  vmagentdata: {}
