{
 "title": "RDS",
 "description": "Dashboard for RDS based on metrics from AWS CloudWatch metrics stream",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "DB_Instance_Identifier",
    "label": "DB Instance Identifier",
    "query": {
     "query": "label_values(amazonaws_com_AWS_RDS_CPUUtilization{}, DBInstanceIdentifier)"
    }
   },
   {
    "name": "Cloud_Region",
    "label": "Cloud Region",
    "query": {
     "query": "label_values(amazonaws_com_AWS_RDS_CPUUtilization{}, cloud_region)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "The percentage of CPU Utilization.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (DBInstanceIdentifier, cloud_region) (amazonaws_com_AWS_RDS_CPUUtilization{DBInstanceIdentifier=~\"$DB_Instance_Identifier\", cloud_region=\"$Cloud_Region\"})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Number of DB Connections",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (DBInstanceIdentifier, cloud_region) (amazonaws_com_AWS_RDS_DatabaseConnections{DBInstanceIdentifier=~\"$DB_Instance_Identifier\", cloud_region=\"$Cloud_Region\"})"
    }
   ]
  },
  {
   "title": "EBS Byte Balance",
   "type": "timeseries",
   "description": "The percentage of throughput credits remaining in the burst bucket of your RDS database. This metric is available for basic monitoring only.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (DBInstanceIdentifier, cloud_region) (amazonaws_com_AWS_RDS_EBSByteBalance_{DBInstanceIdentifier=~\"$DB_Instance_Identifier\", cloud_region=\"$Cloud_Region\"})"
    }
   ]
  },
  {
   "title": "EBS I/O Balance",
   "type": "timeseries",
   "description": "The percentage of I/O credits remaining in the burst bucket of your RDS database. This metric is available for basic monitoring only.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (DBInstanceIdentifier, cloud_region) (amazonaws_com_AWS_RDS_EBSIOBalance_{DBInstanceIdentifier=~\"$DB_Instance_Identifier\", cloud_region=\"$Cloud_Region\"})"
    }
   ]
  }
 ]
}